# language: emacs-lisp
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH="$HOME/.evm/bin:$PATH"
  - export PATH="$HOME/.cask/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

script:
  - emacs --version
  - make test
