(defun color-theme-bitemyapp ()
  (interactive)
  (color-theme-install
   '(color-theme-bitemyapp
      ((background-color . "#010404")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#f8df16")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#0d4519"))))
     (font-lock-builtin-face ((t (:foreground "#cf7372"))))
     (font-lock-comment-face ((t (:foreground "#559f25"))))
     (font-lock-function-name-face ((t (:foreground "#2cf68e"))))
     (font-lock-keyword-face ((t (:foreground "#6c95d5"))))
     (font-lock-string-face ((t (:foreground "#eca655"))))
     (font-lock-type-face ((t (:foreground"#19fa3f"))))
     (font-lock-constant-face ((t (:foreground "#eeeeec"))))
     (font-lock-variable-name-face ((t (:foreground "#f8f8f7"))))
     (minibuffer-prompt ((t (:foreground "#cf72b7" :bold t))))
     (font-lock-warning-face ((t (:foreground "#FF0000" :bold t))))
     )))
(provide 'color-theme-bitemyapp)
